### ISSUE TITLE
fork ?

### ISSUE THREAD

**Issue by timothylhuillier** [hoboman313/huegasm#1]
It's possible to fork your project and add my personal adjustement ?

If yes, it's possible to have explication for install your project ?
Thanks.

**Comment by hoboman313** [comment]
I am afraid I chose not to open source huegasm. This repository is here strictly for the purpose of hosting huegasm.com via github pages.

**Comment by hoboman313** [comment]
Needless to say the situation has changed. Fork and adjust away!
