### ISSUE TITLE
D:

### ISSUE THREAD

**Issue by zethussuen** [hoboman313/huegasm#2]
am a designer/fe-dev. how can i help you on this project?

**Comment by hoboman313** [comment]
Hmm.. I'm currently working on modernizing the code and optimizing some things after which I'll be working on creating a Cordova hybrid app for Android and iOS.

This is a 100% fe project built on ember. You can help by creating issues for things you feel could be made better and working on pull request for them.

**Comment by zethussuen** [comment]
Oh cool. Would love to see this wrapped up in Electron for desktop use. I've got a decent amount of Ember experience for front-end/design. Will take a more thorough look through the codebase and app itself and see what I'd look to improve. 

Thanks!
