### ISSUE TITLE
Chrome tab is muted when I start listening to 'Chrome Tab'

### ISSUE THREAD

**Issue by wodiesan** [hoboman313/huegasm#4]
This is for the Chrome extension (Win 10); this only started happening approximately one week ago.

- The audio returns the moment I press 'Stop Listening'. The bulb colors all remained static.
- Only the relevant tab becomes muted. The audio was fine in another open YouTube tab.
- Switching over to the 'System' option brings up the permissions pop-up, but nothing seems to happen after I click 'Share' (I made sure that 'Share Audio' was checked.
- The icon isn't animated anymore when I start listening. The blue icon on the tab still appears normally.
- 'Reset Settings' didn't change anything. 

Previously I was having some minor issues with bulbs flashing but never changing colors. It turned out that the bulbs that were set through color temp rather than hsv (through a Hue Pro preset, though the app calls this option 'hue') were the ones with this issue. Once I made a preset with every bulb set through hsv this problem went away.

**Comment by hoboman313** [comment]
Hhhhmm... having trouble reproducing this one. Did you try doing a fresh re-install of the extension?

Maybe you can help me debug your issue. When you right click on the Huegasm icon and select "Insepect Popup". You should see a popup that looks like this:
![1](https://cloud.githubusercontent.com/assets/595980/26518625/cc06c5c4-4268-11e7-9bd2-3162cb7231ff.png)
Could you let me know if you see any errors there?

Also if you click on "background page" on the extension page it'll show you a similar view. Let me know if you see any errors in the console tab there.
![2](https://cloud.githubusercontent.com/assets/595980/26518639/0ae0684a-4269-11e7-8cc0-cd48f4143188.png)

**Comment by wodiesan** [comment]
The one thing that I forgot to try was to disable and re-enable it. As it turned out, that was the one thing to fix the issues. Thanks, and sorry to waste your time on a long weekend!
