### ISSUE TITLE
chrome extension

### ISSUE THREAD

**Issue by aycgit** [hoboman313/huegasm#5]
i love the chrome extension but will it keep being premium or are you going to make it free(i have no problems with ads). I am not able to buy things because of my parents :). Not asking you to give it but just if you have any plans.

**Comment by hoboman313** [comment]
AFAIK, it's not possible to monetize Chrome extensions through ads and there is no legit ad network for it yet. I have designed the extension to be pretty lenient in terms of checking for payments. If you promise to not to share it elsewhere, I can PM you the command to trick the extension into thinking you've paid.

And of course, if you like the extension, feel free to leave a review. :D

**Comment by aycgit** [comment]
i would be happy with that trick but im going to leave a good review anyway :)

**Comment by hoboman313** [comment]
I just emailed the email you have associated with your github account.

Enjoy.
